### ISSUE TITLE
InitializeAuth method missing

### ISSUE THREAD

**Issue by jbk75** [Zerg00s/XSOM#1]
Hi,
I'm trying your example but InitializeAuth method is missing from the Authenticator class...

Regards
Johann

**Comment by jbk75** [comment]
Found it in:
https://github.com/Zerg00s/XSOM/blob/master/XSOM/Authenticator.cs

**Comment by Zerg00s** [comment]
Hi @jbk75, Tell me if it still works. I haven't used this solution in a while. :)
